// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDICMrYbFAakAIRaDUUqJ52EYTnxXHYCAc',
    appId: '1:501718082787:web:439c3d454795001b3011d6',
    messagingSenderId: '501718082787',
    projectId: 'fall-detection-9a982',
    authDomain: 'fall-detection-9a982.firebaseapp.com',
    databaseURL: 'https://fall-detection-9a982-default-rtdb.firebaseio.com',
    storageBucket: 'fall-detection-9a982.firebasestorage.app',
    measurementId: 'G-6JSEPTSK1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSXjoXGwyWoV3OqGzJ59yUG1yEzBmv9HU',
    appId: '1:501718082787:android:9bdddf5fef3e784c3011d6',
    messagingSenderId: '501718082787',
    projectId: 'fall-detection-9a982',
    databaseURL: 'https://fall-detection-9a982-default-rtdb.firebaseio.com',
    storageBucket: 'fall-detection-9a982.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfMWOlOaHsqaBv5X3MF4Ak46EGzhOHtqI',
    appId: '1:501718082787:ios:530f8c6f04b7cc8a3011d6',
    messagingSenderId: '501718082787',
    projectId: 'fall-detection-9a982',
    databaseURL: 'https://fall-detection-9a982-default-rtdb.firebaseio.com',
    storageBucket: 'fall-detection-9a982.firebasestorage.app',
    iosBundleId: 'com.example.difds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfMWOlOaHsqaBv5X3MF4Ak46EGzhOHtqI',
    appId: '1:501718082787:ios:530f8c6f04b7cc8a3011d6',
    messagingSenderId: '501718082787',
    projectId: 'fall-detection-9a982',
    databaseURL: 'https://fall-detection-9a982-default-rtdb.firebaseio.com',
    storageBucket: 'fall-detection-9a982.firebasestorage.app',
    iosBundleId: 'com.example.difds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDICMrYbFAakAIRaDUUqJ52EYTnxXHYCAc',
    appId: '1:501718082787:web:6d6f643467ba70e93011d6',
    messagingSenderId: '501718082787',
    projectId: 'fall-detection-9a982',
    authDomain: 'fall-detection-9a982.firebaseapp.com',
    databaseURL: 'https://fall-detection-9a982-default-rtdb.firebaseio.com',
    storageBucket: 'fall-detection-9a982.firebasestorage.app',
    measurementId: 'G-TNBX5FWQJC',
  );
}
